//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSalesSystem.Shared.Domain.Globalization.Resources.Validations {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppValidations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppValidations() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebSalesSystem.Shared.Domain.Globalization.Resources.Validations.AppValidations", typeof(AppValidations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There is already a record with the specified data.
        /// </summary>
        public static string ERROR_DUPLICATERECORD {
            get {
                return ResourceManager.GetString("ERROR_DUPLICATERECORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Field &apos;{PropertyName}&apos; cannot be empty.
        /// </summary>
        public static string ERROR_EMPTY {
            get {
                return ResourceManager.GetString("ERROR_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An exception occurred.
        /// </summary>
        public static string ERROR_EXCEPTION {
            get {
                return ResourceManager.GetString("ERROR_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Field &apos;{PropertyName}&apos; is not a valid e-mail address.
        /// </summary>
        public static string ERROR_INVALIDEMAIL {
            get {
                return ResourceManager.GetString("ERROR_INVALIDEMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Option submitted for field &apos;{PropertyName}&apos; is invalid.
        /// </summary>
        public static string ERROR_INVALIDOPTION {
            get {
                return ResourceManager.GetString("ERROR_INVALIDOPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Value of &apos;{PropertyName}&apos; must be between {MinLength} and {MaxLength}.
        /// </summary>
        public static string ERROR_NUMBERLENGHT {
            get {
                return ResourceManager.GetString("ERROR_NUMBERLENGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Value of &apos;{PropertyName}&apos; must be less than {MaxLength}.
        /// </summary>
        public static string ERROR_NUMBERMAXLENGHT {
            get {
                return ResourceManager.GetString("ERROR_NUMBERMAXLENGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Value of &apos;{PropertyName}&apos; must be greater than {MinLength}.
        /// </summary>
        public static string ERROR_NUMBERMINLEGHT {
            get {
                return ResourceManager.GetString("ERROR_NUMBERMINLEGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Record not found.
        /// </summary>
        public static string ERROR_RECORDNOTFOUND {
            get {
                return ResourceManager.GetString("ERROR_RECORDNOTFOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Field &apos;{PropertyName}&apos; is required.
        /// </summary>
        public static string ERROR_REQUIRED {
            get {
                return ResourceManager.GetString("ERROR_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An unespected error ocurred.
        /// </summary>
        public static string ERROR_SERVERERROR {
            get {
                return ResourceManager.GetString("ERROR_SERVERERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Field &apos;{PropertyName}&apos; must be between {MinLength} and {MaxLength} characters long.
        /// </summary>
        public static string ERROR_STRINGLENGHT {
            get {
                return ResourceManager.GetString("ERROR_STRINGLENGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Field &apos;{PropertyName}&apos; must be less than {MaxLength} characters long.
        /// </summary>
        public static string ERROR_STRINGMAXLENGHT {
            get {
                return ResourceManager.GetString("ERROR_STRINGMAXLENGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Field &apos;{PropertyName}&apos; must be greater than {MinLength} characters long.
        /// </summary>
        public static string ERROR_STRINGMINLENGHT {
            get {
                return ResourceManager.GetString("ERROR_STRINGMINLENGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No subtenant has been provided.
        /// </summary>
        public static string ERROR_SUBTENANTNOTPROVIDED {
            get {
                return ResourceManager.GetString("ERROR_SUBTENANTNOTPROVIDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No tenant has been provided.
        /// </summary>
        public static string ERROR_TENANTNOTPROVIDED {
            get {
                return ResourceManager.GetString("ERROR_TENANTNOTPROVIDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a One or more validation errors occurred.
        /// </summary>
        public static string ERROR_VALIDATIONFAILED {
            get {
                return ResourceManager.GetString("ERROR_VALIDATIONFAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Data loaded successfully.
        /// </summary>
        public static string SUCCESS_DATA {
            get {
                return ResourceManager.GetString("SUCCESS_DATA", resourceCulture);
            }
        }
    }
}
