//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSalesSystem.Shared.Domain.Globalization.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppStrings() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebSalesSystem.Shared.Domain.Globalization.Resources.Strings.AppStrings", typeof(AppStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Description.
        /// </summary>
        public static string SUBTENANT_DESCRIPTION {
            get {
                return ResourceManager.GetString("SUBTENANT_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email.
        /// </summary>
        public static string SUBTENANT_EMAIL {
            get {
                return ResourceManager.GetString("SUBTENANT_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Name.
        /// </summary>
        public static string SUBTENANT_NAME {
            get {
                return ResourceManager.GetString("SUBTENANT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Data base provider.
        /// </summary>
        public static string TENANT_DBPROVIDER {
            get {
                return ResourceManager.GetString("TENANT_DBPROVIDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Description.
        /// </summary>
        public static string TENANT_DESCRIPTION {
            get {
                return ResourceManager.GetString("TENANT_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email.
        /// </summary>
        public static string TENANT_EMAIL {
            get {
                return ResourceManager.GetString("TENANT_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Use email confirmation.
        /// </summary>
        public static string TENANT_EMAILCONFIRMATION {
            get {
                return ResourceManager.GetString("TENANT_EMAILCONFIRMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Allow external register.
        /// </summary>
        public static string TENANT_EXTERNALREGISTRATION {
            get {
                return ResourceManager.GetString("TENANT_EXTERNALREGISTRATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Name.
        /// </summary>
        public static string TENANT_NAME {
            get {
                return ResourceManager.GetString("TENANT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Storage name.
        /// </summary>
        public static string TENANT_STORAGENAME {
            get {
                return ResourceManager.GetString("TENANT_STORAGENAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Storage type.
        /// </summary>
        public static string TENANT_STORAGETYPE {
            get {
                return ResourceManager.GetString("TENANT_STORAGETYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Use subtenants.
        /// </summary>
        public static string TENANT_SUBTENANTS {
            get {
                return ResourceManager.GetString("TENANT_SUBTENANTS", resourceCulture);
            }
        }
    }
}
